import type { SymbolViewProps } from "expo-symbols";

// Every app icon has a native SF Symbol and a bundled Material Symbol.
export const androidIcons = {
  archivebox: "archive",
  "arrow.clockwise": "refresh",
  "arrow.down": "arrow_downward",
  "arrow.down.right.and.arrow.up.left": "close_fullscreen",
  "arrow.left": "arrow_back",
  "arrow.right": "arrow_forward",
  "arrow.triangle.branch": "fork_right",
  "arrow.triangle.pull": "merge",
  "arrow.triangle.swap": "swap_horiz",
  "arrow.turn.down.right": "subdirectory_arrow_right",
  "arrow.up": "arrow_upward",
  "arrow.up.left": "north_west",
  "arrow.up.right": "north_east",
  camera: "photo_camera",
  "chart.bar": "bar_chart",
  checkmark: "check",
  "checkmark.circle": "check_circle",
  "checkmark.circle.fill": "check_circle",
  "checkmark.seal": "verified",
  "checkmark.square.fill": "check_box",
  "chevron.down": "expand_more",
  "chevron.left": "chevron_left",
  "chevron.right": "chevron_right",
  "chevron.up": "expand_less",
  circle: "circle",
  "circle.dotted": "pending",
  "circle.lefthalf.filled": "contrast",
  clock: "schedule",
  "clock.arrow.circlepath": "history",
  command: "keyboard_command_key",
  display: "desktop_windows",
  doc: "description",
  "doc.badge.plus": "note_add",
  "doc.on.doc": "content_copy",
  "doc.text": "description",
  ellipsis: "more_horiz",
  "exclamationmark.circle": "error",
  folder: "folder",
  "folder.fill": "folder_open",
  gearshape: "settings",
  hammer: "construction",
  "hand.raised": "pan_tool",
  italic: "format_italic",
  keyboard: "keyboard",
  "keyboard.chevron.compact.down": "keyboard_hide",
  laptopcomputer: "laptop_mac",
  link: "link",
  lock: "lock",
  "lock.open": "lock_open",
  "lock.shield": "shield_lock",
  magnifyingglass: "search",
  "minus.circle": "remove_circle",
  number: "tag",
  paperclip: "attach_file",
  "pause.circle": "pause_circle",
  pencil: "edit",
  "person.2": "group",
  "person.crop.circle": "account_circle",
  photo: "image",
  pin: "push_pin",
  "pin.fill": "push_pin",
  plus: "add",
  "point.topleft.down.to.point.bottomright.curvepath": "route",
  "puzzlepiece.extension": "extension",
  "qrcode.viewfinder": "qr_code_scanner",
  "sidebar.left": "left_panel_open",
  "slider.horizontal.3": "tune",
  sparkle: "auto_awesome",
  sparkles: "auto_awesome",
  square: "check_box_outline_blank",
  "square.and.arrow.up": "ios_share",
  "square.and.pencil": "edit_square",
  stop: "stop",
  "stop.fill": "stop",
  terminal: "terminal",
  "text.bubble": "chat_bubble",
  underline: "format_underlined",
  viewfinder: "center_focus_strong",
  "waveform.path": "monitoring",
  xmark: "close",
  "xmark.circle": "cancel",
} as const satisfies Record<
  string,
  NonNullable<Exclude<SymbolViewProps["name"], string>["android"]>
>;

export type IconName = keyof typeof androidIcons;
